name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_leetcode: yes
          leetcode_user: DIGVIJAYSINH_SARVAIYA


